version: '3.8'

services:
  # Servicio de la aplicación de cursos
  courses-api:
    build:
      context: ./courses-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://root:root@mongodb:27017
      - RABBITMQ_URI=amqp://root:root@rabbitmq:5672/
    depends_on:
      - mongodb
      - rabbitmq

  # Servicio de la aplicación de inscripciones
  inscriptions-api:
    build:
      context: ./inscriptions-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=inscriptions
      - USERS_API_URL=http://users-api:8082
      - COURSES_API_URL=http://courses-api:8080
    depends_on:
      - mysql
      - courses-api

  # Servicio de la aplicación de búsqueda
  search-api:
    build:
      context: ./search-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - solr
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SOLR_HOST=solr
      - SOLR_PORT=8983

  # Servicio de MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inscriptions
    ports:
      - "3307:3306"

  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Servicio de SolR
  solr:
    image: solr:8.11.1
    ports:
      - "8983:8983"      # Expone el puerto 8983 para acceder a la interfaz de SolR
    volumes:
      - ./search-api/solr-config:/opt/solr/server/solr/mycores/courses/conf  # Monta la configuración
    
    command: solr-create -c courses


  # Servicio de RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Puerto para conexiones de aplicación
      - "15672:15672"    # Puerto para la interfaz de gestión de RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

volumes:
  mongodb_data: