version: '3.8'

services:
  # Servicio de la aplicación en Go
  search-api:
    build:
      context: .
    ports:
      - "8082:8082"      # Expone el puerto 8082 para acceder a la API de búsqueda
    depends_on:
      - solr
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SOLR_HOST=solr
      - SOLR_PORT=8983

  # Servicio de SolR
  solr:
    image: solr:8.11.1
    ports:
      - "8983:8983"      # Expone el puerto 8983 para acceder a la interfaz de SolR
    volumes:
      - ./solr-config:/opt/solr/server/solr/mycores/courses/conf  # Monta la configuración
    environment:
      - SOLR_CORE=courses
    entrypoint:
      - bash
      - "-c"
      - |
        precreate-core $SOLR_CORE && solr-foreground

  # Servicio de RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Puerto para conexiones de aplicación
      - "15672:15672"    # Puerto para la interfaz de gestión de RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
